baseURL = "http://kyamawork.info/"
languageCode = "ja"
title = "技術ブログとか"

googleAnalytics = "UA-117981223-1"

pygmentsCodefences = true
pygmentsUseClasses = true

[taxonomies]
  tag = "tags"
  category = "categories"
